import type { Listing, Category } from './types';
export const MOCK_CATEGORIES: Category[] = [
  { id: 'restaurants', name: 'Restaurants', slug: 'restaurants', icon: 'UtensilsCrossed' },
  { id: 'shopping', name: 'Shopping', slug: 'shopping', icon: 'ShoppingBag' },
  { id: 'cafes', name: 'Cafes', slug: 'cafes', icon: 'Coffee' },
  { id: 'hotels', name: 'Hotels', slug: 'hotels', icon: 'BedDouble' },
  { id: 'beauty', name: 'Beauty', slug: 'beauty', icon: 'Sparkles' },
  { id: 'services', name: 'Services', slug: 'services', icon: 'Wrench' },
];
export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'The Golden Spoon',
    summary: 'A modern bistro offering a fusion of local and international cuisine.',
    description: 'The Golden Spoon is a culinary gem located in the heart of the city. Our chefs use only the freshest local ingredients to create a menu that is both innovative and comforting. With a cozy ambiance and an extensive wine list, it\'s the perfect spot for a romantic dinner or a special celebration.',
    category: 'restaurants',
    location: 'Downtown',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1974&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?q=80&w=2071&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544739313-6a8db0f67b8f?q=80&w=1974&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviews: 256,
    tags: ['fine dining', 'local ingredients', 'wine bar'],
    details: {
      address: '123 Main Street, Anytown, USA',
      phone: '(555) 123-4567',
      website: 'thegoldenspoon.com',
      hours: 'Mon-Sat: 5pm - 11pm',
    },
  },
  {
    id: '2',
    title: 'Artisan Roast',
    summary: 'Specialty coffee shop with house-roasted beans and delicious pastries.',
    description: 'Artisan Roast is more than just a coffee shop; it\'s a community hub for coffee lovers. We ethically source our beans from around the world and roast them in-house to perfection. Pair your favorite brew with one of our freshly baked pastries for the ultimate experience.',
    category: 'cafes',
    location: 'Arts District',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1974&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1511920183276-5941b6fb4513?q=80&w=1974&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=1974&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviews: 412,
    tags: ['specialty coffee', 'bakery', 'free wifi'],
    details: {
      address: '456 Oak Avenue, Anytown, USA',
      phone: '(555) 987-6543',
      website: 'artisanroast.com',
      hours: 'Mon-Sun: 7am - 6pm',
    },
  },
  {
    id: '3',
    title: 'The Minimalist Boutique',
    summary: 'Curated collection of modern apparel and lifestyle goods.',
    description: 'Discover your new favorite wardrobe staples at The Minimalist Boutique. We believe in quality over quantity, offering a carefully curated selection of timeless pieces from independent designers. Our focus is on sustainable materials and ethical production.',
    category: 'shopping',
    location: 'Uptown',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?q=80&w=1974&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1594969155368-f19461ade3d9?q=80&w=1974&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviews: 134,
    tags: ['fashion', 'sustainable', 'independent designers'],
    details: {
      address: '789 Pine Lane, Anytown, USA',
      phone: '(555) 234-5678',
      website: 'minimalistboutique.com',
      hours: 'Tue-Sun: 11am - 7pm',
    },
  },
  {
    id: '4',
    title: 'Serenity Spa & Wellness',
    summary: 'An urban oasis for relaxation, rejuvenation, and holistic healing.',
    description: 'Escape the hustle and bustle of city life at Serenity Spa. We offer a wide range of services including massages, facials, and body treatments, all designed to promote wellness and restore balance. Our tranquil environment and expert therapists will leave you feeling refreshed and renewed.',
    category: 'beauty',
    location: 'Midtown',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=1974&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1598800029444-c9947328673a?q=80&w=1974&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1974&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviews: 302,
    tags: ['massage', 'facials', 'wellness'],
    details: {
      address: '101 Maple Drive, Anytown, USA',
      phone: '(555) 345-6789',
      website: 'serenityspa.com',
      hours: 'Mon-Sun: 9am - 8pm',
    },
  },
  {
    id: '5',
    title: 'The Grand Vista Hotel',
    summary: 'Luxury hotel with breathtaking city views and world-class amenities.',
    description: 'Experience unparalleled luxury at The Grand Vista Hotel. Our elegantly appointed rooms, rooftop pool, and award-winning restaurant make for an unforgettable stay. Whether you\'re traveling for business or pleasure, our attentive staff is dedicated to making your visit exceptional.',
    category: 'hotels',
    location: 'Downtown',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbb5eb?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1925&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?q=80&w=2070&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviews: 1240,
    tags: ['luxury', 'rooftop pool', 'concierge'],
    details: {
      address: '202 Sky High Blvd, Anytown, USA',
      phone: '(555) 456-7890',
      website: 'grandvistahotel.com',
      hours: 'Open 24/7',
    },
  },
  {
    id: '6',
    title: 'QuickFix Auto Repair',
    summary: 'Reliable and honest auto repair services for all makes and models.',
    description: 'At QuickFix Auto, we understand that car trouble is a major inconvenience. Our team of certified mechanics is committed to providing fast, reliable, and transparent service to get you back on the road safely. From oil changes to major repairs, we\'ve got you covered.',
    category: 'services',
    location: 'Industrial Park',
    image: 'https://images.unsplash.com/photo-1567789863910-1d6c983781e8?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1623194193538-9f0f73b3de19?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1580552193584-71f49c1c9114?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1617153213546-8c454a0a1332?q=80&w=2070&auto=format&fit=crop',
    ],
    rating: 4.6,
    reviews: 88,
    tags: ['auto repair', 'certified mechanics', 'oil change'],
    details: {
      address: '303 Industrial Way, Anytown, USA',
      phone: '(555) 567-8901',
      website: 'quickfixauto.com',
      hours: 'Mon-Fri: 8am - 6pm',
    },
  },
];